defaults:
  server:
    # TODO: is it possible to specify these as env but have default values??
    publicUrl:                      !env PUBLIC_URL
    port:                           !env:number PORT
    env:                            !env:bool NODE_ENV
    forceSSL:                       !env:bool FORCE_SSL
    trustProxy:                     !env:bool TRUST_PROXY

test:
  server:
    publicUrl:                    'http://localhost:60415'
    port:                         60415
